### ISSUE TITLE
front end to-do

### ISSUE THREAD

**Issue by biantris** [biantris/asktris#31]
see https://github.com/asklisa/fullstack-challenge#frontend-exercise

- [x] Implement a simple dashboard that has three separated screens:
     - [x] First screen will only display a form that will allow to submit a scan result.
     - [x] Second screen will only display the list of security scan results. The columns of the list should be: repository name, scan status, findings (is the quantity of findings and should be displayed on a badge/label component, [example here](https://react.semantic-ui.com/elements/label/)), and the according timestamp (i.e.: if Status is Queued, use QueuedAt).
     - [x] Third screen will only display the list of findings for a selected security scan (selected from the screen number 2) with the following 4 columns: RuleId, Description, Severity and Path name : line number.
